"""empty message

Revision ID: 338909481a38
Revises: 
Create Date: 2019-03-14 22:20:35.130379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338909481a38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('reviewer', sa.String(length=80), nullable=False),
    sa.Column('professor', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=80), nullable=False),
    sa.Column('score1', sa.Float(), nullable=False),
    sa.Column('score2', sa.Float(), nullable=False),
    sa.Column('score3', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('school', sa.String(length=10), nullable=True),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('reviewer', 'professor', 'course')
    )
    op.create_table('prof_course',
    sa.Column('cid', sa.String(length=20), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cid'], ['course.id'], ),
    sa.ForeignKeyConstraint(['pid'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('cid', 'pid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prof_course')
    op.drop_table('review')
    op.drop_table('professor')
    op.drop_table('course')
    # ### end Alembic commands ###
