"""empty message

Revision ID: 343ace7b95db
Revises: 
Create Date: 2019-03-16 15:47:09.773762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343ace7b95db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('cid', sa.String(length=20), nullable=False))
    op.add_column('course', sa.Column('school', sa.String(length=10), nullable=False))
    op.create_unique_constraint(None, 'course', ['name'])
    op.add_column('prof_course', sa.Column('cname', sa.String(length=80), nullable=True))
    op.add_column('prof_course', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('prof_course', sa.Column('pname', sa.String(length=80), nullable=True))
    op.drop_constraint('prof_course_pid_fkey', 'prof_course', type_='foreignkey')
    op.drop_constraint('prof_course_cid_fkey', 'prof_course', type_='foreignkey')
    op.create_foreign_key(None, 'prof_course', 'course', ['cname'], ['name'])
    op.create_foreign_key(None, 'prof_course', 'professor', ['pname'], ['name'])
    op.drop_column('prof_course', 'cid')
    op.drop_column('prof_course', 'pid')
    op.create_unique_constraint(None, 'professor', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'professor', type_='unique')
    op.add_column('prof_course', sa.Column('pid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('prof_course', sa.Column('cid', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'prof_course', type_='foreignkey')
    op.drop_constraint(None, 'prof_course', type_='foreignkey')
    op.create_foreign_key('prof_course_cid_fkey', 'prof_course', 'course', ['cid'], ['id'])
    op.create_foreign_key('prof_course_pid_fkey', 'prof_course', 'professor', ['pid'], ['id'])
    op.drop_column('prof_course', 'pname')
    op.drop_column('prof_course', 'id')
    op.drop_column('prof_course', 'cname')
    op.drop_constraint(None, 'course', type_='unique')
    op.drop_column('course', 'school')
    op.drop_column('course', 'cid')
    # ### end Alembic commands ###
