"""empty message

Revision ID: ba618b8c67a2
Revises: 
Create Date: 2019-03-16 21:05:17.068248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba618b8c67a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'review', 'prof_course', ['pname', 'cname'], ['pname', 'cname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    # ### end Alembic commands ###
