"""empty message

Revision ID: bd9eced2b72e
Revises: de4bfb81997f
Create Date: 2019-03-20 17:12:22.469107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd9eced2b72e'
down_revision = 'de4bfb81997f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('reviewer', sa.String(length=80), nullable=False),
    sa.Column('pname', sa.String(length=80), nullable=False),
    sa.Column('cname', sa.String(length=80), nullable=False),
    sa.Column('score1', sa.Float(), nullable=False),
    sa.Column('score2', sa.Float(), nullable=False),
    sa.Column('score3', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('school', sa.String(length=10), nullable=True),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('advice', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['pname', 'cname'], ['prof_course.pname', 'prof_course.cname'], ),
    sa.PrimaryKeyConstraint('reviewer', 'pname', 'cname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
