"""empty message

Revision ID: c41e5fdd7a03
Revises: 338909481a38
Create Date: 2019-03-14 22:23:59.077072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41e5fdd7a03'
down_revision = '338909481a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('advice', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'advice')
    # ### end Alembic commands ###
